"""Export the response schemas the frontend mirrors into a committed snapshot.

The frontend cannot import Python, so the contract between the two halves of this
repository has to cross a file. This writes that file; ``tests/unit/
test_openapi_snapshot.py`` fails if it drifts from what the app actually serves, and
``frontend/src/test/contract.test.ts`` fails if the TypeScript types drift from it.

Run this after any change to a response schema, then commit the result:

    python -m scripts.export_openapi

Only the schemas listed in ``MIRRORED`` are exported. An unrelated backend model is
nobody's business, but a change to one of these is a change to the API.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from app.main import app

#: Backend schema name -> the TypeScript type in ``frontend/src/api/types.ts`` that
#: claims to mirror it. Kept here, next to the export, so adding a mirrored schema is a
#: deliberate act rather than a side effect of dumping everything.
MIRRORED: dict[str, str] = {
    "CalculationResponse": "CalculationResponse",
    "CaseListResponse": "CaseList",
    "CaseSummaryResponse": "CaseSummary",
    "DisputeDetailResponse": "CaseDetail",
    "EvidenceResponse": "EvidenceResponse",
    "FindingResponse": "FindingResponse",
    "HypothesisResponse": "HypothesisResponse",
    "InvestigationResponse": "InvestigationResponse",
    "MoneyResponse": "MoneyResponse",
    "ResolutionOptionResponse": "ResolutionOptionResponse",
    "ReviewResponse": "ReviewResponse",
}

#: ``/capabilities`` is not modelled by a response class -- it is built from a dict and
#: published as ``additionalProperties: true`` -- so there is no schema to compare
#: ``Capabilities`` against and it is deliberately absent from the snapshot.
SNAPSHOT_PATH = (
    Path(__file__).resolve().parents[2] / "frontend" / "src" / "api" / "openapi.snapshot.json"
)


def build_snapshot() -> dict[str, Any]:
    """Return the snapshot document, or raise if a mirrored schema has disappeared."""
    schemas = app.openapi()["components"]["schemas"]

    missing = sorted(name for name in MIRRORED if name not in schemas)
    if missing:
        raise SystemExit(
            f"MIRRORED names schemas that no longer exist: {missing}. "
            "A response schema was renamed or removed; update MIRRORED and the frontend."
        )

    return {
        "_comment": (
            "Generated by `python -m scripts.export_openapi`. Do not edit by hand. "
            "Regenerate when a mirrored response schema changes, and commit the result."
        ),
        "typescript_types": dict(MIRRORED),
        "schemas": {name: schemas[name] for name in sorted(MIRRORED)},
    }


def render() -> str:
    return json.dumps(build_snapshot(), indent=2, sort_keys=True) + "\n"


def main() -> None:
    SNAPSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)
    SNAPSHOT_PATH.write_text(render(), encoding="utf-8")
    print(f"wrote {len(MIRRORED)} schemas to {SNAPSHOT_PATH}")


if __name__ == "__main__":
    main()
