/**
 * The frontend/backend contract, enforced by the build.
 *
 * This exists because the mismatch it guards against was invisible for a while.
 * `CaseSummary` claimed a `description` and a `review_count` that the list endpoint
 * has never sent, and `CaseDetail` claimed a `source_document` that no endpoint
 * sends at all. `tsc` was happy, the unit tests were happy, and the queue rendered
 * a blank line where the description should have been. Nothing failed because both
 * sides were checked against hand-written copies of each other.
 *
 * So this compares against the backend's real output. `openapi.snapshot.json` is
 * generated by `python -m scripts.export_openapi`, and
 * `backend/tests/unit/test_openapi_snapshot.py` fails if that file stops matching
 * what the app serves -- which is what keeps this from quietly becoming another
 * hand-maintained copy.
 *
 * What it checks, per mirrored type:
 *   - the property sets are identical (nothing extra, nothing missing);
 *   - each property's kind matches (string/number/boolean/array/object/named);
 *   - nullability matches, because `null` and "absent" are different claims;
 *   - a property the backend requires is not optional here.
 *
 * A note on optionality. Pydantic omits a field with a default from JSON Schema's
 * `required`, but the serializer always writes it, so every property below really
 * does arrive in every response. The check is therefore one-directional on purpose:
 * required-here-but-optional-in-the-backend is tolerated (the defaults guarantee it
 * is present), while required-in-the-backend-but-optional-here is an error, because
 * that one really can bite at runtime.
 */

import { describe, expect, it } from 'vitest'
import ts from 'typescript'

import snapshotRaw from '../api/openapi.snapshot.json'
import typesRaw from '../api/types.ts?raw'

// ---------------------------------------------------------------------------
// Parse types.ts into a map of named declarations.
// ---------------------------------------------------------------------------

const sourceFile = ts.createSourceFile(
  'types.ts',
  typesRaw,
  ts.ScriptTarget.Latest,
  true,
  ts.ScriptKind.TS,
)

const interfaces = new Map<string, ts.InterfaceDeclaration>()
const aliases = new Map<string, ts.TypeAliasDeclaration>()

sourceFile.forEachChild((node) => {
  if (ts.isInterfaceDeclaration(node)) interfaces.set(node.name.text, node)
  else if (ts.isTypeAliasDeclaration(node)) aliases.set(node.name.text, node)
})

type Kind = 'string' | 'number' | 'boolean' | 'object' | 'array' | 'named' | 'unknown'

interface Shape {
  kind: Kind
  nullable: boolean
  /** Populated for `array`. */
  element?: Shape
  /** Populated for `named`; a TypeScript type name. */
  ref?: string
}

function isNullLiteral(node: ts.TypeNode): boolean {
  return ts.isLiteralTypeNode(node) && node.literal.kind === ts.SyntaxKind.NullKeyword
}

/** The primitive a literal type carries, or `'other'` for booleans and the like. */
function literalPrimitive(node: ts.TypeNode): 'string' | 'number' | 'other' {
  if (!ts.isLiteralTypeNode(node)) return 'other'
  const literal = (node as ts.LiteralTypeNode).literal
  if (ts.isStringLiteral(literal)) return 'string'
  if (ts.isNumericLiteral(literal)) return 'number'
  return 'other'
}

function resolveTypeNode(node: ts.TypeNode | undefined): Shape {
  if (!node) return { kind: 'unknown', nullable: false }

  if (ts.isUnionTypeNode(node)) {
    const nonNull = node.types.filter((part) => !isNullLiteral(part))
    const nullable = nonNull.length !== node.types.length

    if (nonNull.every((part) => ts.isLiteralTypeNode(part))) {
      const primitives = new Set(nonNull.map(literalPrimitive))
      const kind: Kind = primitives.has('string')
        ? 'string'
        : primitives.has('number')
          ? 'number'
          : 'unknown'
      return { kind, nullable }
    }

    if (nonNull.length === 1) {
      const inner = resolveTypeNode(nonNull[0])
      return { ...inner, nullable: inner.nullable || nullable }
    }
    return { kind: 'unknown', nullable }
  }

  switch (node.kind) {
    case ts.SyntaxKind.StringKeyword:
      return { kind: 'string', nullable: false }
    case ts.SyntaxKind.NumberKeyword:
      return { kind: 'number', nullable: false }
    case ts.SyntaxKind.BooleanKeyword:
      return { kind: 'boolean', nullable: false }
    default:
      break
  }

  if (ts.isArrayTypeNode(node)) {
    return { kind: 'array', nullable: false, element: resolveTypeNode(node.elementType) }
  }
  if (ts.isTypeLiteralNode(node)) return { kind: 'object', nullable: false }

  if (ts.isTypeReferenceNode(node)) {
    const name = node.typeName.getText(sourceFile)
    if (name === 'Array') {
      return {
        kind: 'array',
        nullable: false,
        element: resolveTypeNode(node.typeArguments?.[0]),
      }
    }
    if (name === 'Record') return { kind: 'object', nullable: false }
    const alias = aliases.get(name)
    if (alias) return resolveTypeNode(alias.type)
    if (interfaces.has(name)) return { kind: 'named', nullable: false, ref: name }
  }

  return { kind: 'unknown', nullable: false }
}

/** Members of an interface, with inherited ones merged in (base first, own wins). */
function membersOf(name: string): Map<string, { type: ts.TypeNode | undefined; optional: boolean }> {
  const out = new Map<string, { type: ts.TypeNode | undefined; optional: boolean }>()
  const decl = interfaces.get(name)
  if (!decl) return out

  for (const clause of decl.heritageClauses ?? []) {
    for (const base of clause.types) {
      for (const [key, value] of membersOf(base.expression.getText(sourceFile))) {
        out.set(key, value)
      }
    }
  }
  for (const member of decl.members) {
    if (ts.isPropertySignature(member) && member.name) {
      out.set(member.name.getText(sourceFile), {
        type: member.type,
        optional: member.questionToken !== undefined,
      })
    }
  }
  return out
}

// ---------------------------------------------------------------------------
// The snapshot.
// ---------------------------------------------------------------------------

interface Snapshot {
  typescript_types: Record<string, string>
  schemas: Record<string, { required?: string[]; properties: Record<string, JsonSchema> }>
}

interface JsonSchema {
  $ref?: string
  type?: string
  enum?: unknown[]
  items?: JsonSchema
  anyOf?: JsonSchema[]
  properties?: Record<string, JsonSchema>
}

const snapshot = snapshotRaw as Snapshot

/** backend schema name -> TypeScript type name, for resolving `$ref`s. */
const backendToTypescript = new Map(
  Object.entries(snapshot.typescript_types).map(([backend, tsName]) => [backend, tsName]),
)

function backendShape(schema: JsonSchema): Shape {
  if (schema.anyOf) {
    const nonNull = schema.anyOf.filter((part) => part.type !== 'null')
    const nullable = nonNull.length !== schema.anyOf.length
    if (nonNull.length === 1) {
      const inner = backendShape(nonNull[0] as JsonSchema)
      return { ...inner, nullable: inner.nullable || nullable }
    }
    return { kind: 'string', nullable }
  }
  if (schema.$ref) {
    const backendName = schema.$ref.split('/').pop() ?? ''
    const tsName = backendToTypescript.get(backendName)
    return tsName
      ? { kind: 'named', nullable: false, ref: tsName }
      : { kind: 'unknown', nullable: false }
  }
  if (schema.enum) return { kind: 'string', nullable: false }

  switch (schema.type) {
    case 'string':
      return { kind: 'string', nullable: false }
    case 'integer':
    case 'number':
      return { kind: 'number', nullable: false }
    case 'boolean':
      return { kind: 'boolean', nullable: false }
    case 'object':
      return { kind: 'object', nullable: false }
    case 'array':
      return {
        kind: 'array',
        nullable: false,
        element: schema.items ? backendShape(schema.items) : { kind: 'unknown', nullable: false },
      }
    default:
      return { kind: 'unknown', nullable: false }
  }
}

/** Named `shapeText`, not `describe`: shadowing vitest's `describe` breaks the suite. */
function shapeText(shape: Shape): string {
  const base = shape.kind === 'named' && shape.ref ? shape.ref : shape.kind
  return shape.nullable ? `${base} | null` : base
}

// ---------------------------------------------------------------------------
// The checks.
// ---------------------------------------------------------------------------

const mirrored = Object.entries(snapshot.typescript_types)

describe('frontend types vs the backend OpenAPI schema', () => {
  it('reads the snapshot', () => {
    expect(mirrored.length).toBeGreaterThan(0)
    expect(Object.keys(snapshot.schemas).sort()).toEqual(
      Object.keys(snapshot.typescript_types).sort(),
    )
  })

  it.each(mirrored)('%s mirrors %s', (backendName, tsName) => {
    const schema = snapshot.schemas[backendName]
    expect(schema, `${backendName} is missing from the snapshot`).toBeDefined()

    const schemaProperties = schema?.properties ?? {}
    const required = new Set(schema?.required ?? [])
    const actual = membersOf(tsName)
    expect(actual.size, `${tsName} is not declared in types.ts`).toBeGreaterThan(0)

    // 1. Nothing invented, nothing forgotten.
    const expectedNames = Object.keys(schemaProperties).sort()
    const actualNames = [...actual.keys()].sort()
    expect(
      actualNames.filter((name) => !expectedNames.includes(name)),
      `${tsName} declares fields the backend does not send: ${actualNames
        .filter((name) => !expectedNames.includes(name))
        .join(', ')}`,
    ).toEqual([])
    expect(
      expectedNames.filter((name) => !actualNames.includes(name)),
      `${tsName} is missing fields the backend sends: ${expectedNames
        .filter((name) => !actualNames.includes(name))
        .join(', ')}`,
    ).toEqual([])

    // 2. Kinds and nullability, per field.
    for (const name of expectedNames) {
      const member = actual.get(name)
      if (!member) continue
      const fromFrontend = resolveTypeNode(member.type)
      const fromBackend = backendShape(schemaProperties[name] as JsonSchema)

      expect(
        shapeText(fromFrontend),
        `${tsName}.${name}: frontend says ${shapeText(fromFrontend)}, backend sends ${shapeText(
          fromBackend,
        )}`,
      ).toBe(shapeText(fromBackend))
    }

    // 3. A field the backend guarantees must not be optional here.
    for (const name of required) {
      const member = actual.get(name)
      if (!member) continue
      expect(member.optional, `${tsName}.${name} is required by the backend but optional here`).toBe(
        false,
      )
    }
  })

  it('rejects a mismatch, so the harness itself is trustworthy', () => {
    // A check that cannot fail is not a check. This asserts the comparator notices a
    // field the backend does not send, by asking it about a name we know is absent.
    const schema = snapshot.schemas.CaseSummaryResponse
    const schemaProperties = schema?.properties ?? {}
    expect(Object.keys(schemaProperties)).not.toContain('description')
    expect(Object.keys(schemaProperties)).not.toContain('review_count')
    expect(Object.keys(schemaProperties)).not.toContain('source_document')
  })
})
